### ISSUE TITLE
Leaping backwards?

### ISSUE THREAD

**Issue by JamesNZL** [ggandor/leap-spooky.nvim#20]
Hey, cheers for your set of leap plugins—they're pretty dang cool.

Just curious—is it not possible to use a backwards leap (ie `S` leap) motion, or am I missing something?

**Comment by ggandor** [comment]
Hi, thanks! `irw` etc. finds text objects in the whole window. You mean you'd like e.g. `irw` to only find matches after the cursor, and `iRw` before, like targets.vim's `inw`/`iNw`? (Two separate motions wouldn't have that much advantage here as in a normal leap jump, because we use these for operations, we couldn't auto-jump to the first target anyway.)

**Comment by JamesNZL** [comment]
Oh 🤦.

I must have been testing the `y3rr` with a leap that *only existed after cursor*, hence my confusion.

Cheers!
